stages:
  # - test
  - build
  - deploy

# test:
#   stage: test
#   script: echo "Running tests"

build:
  stage: build
  script: 
    - node -v && npm -v
    - npm install
    - gulp html
    - gulp css

deploy_development:
  stage: deploy
  script:
    - echo "Deploy to development server"
    - ls -la
    - pwd
    - whoami
  environment:
    name: development
    url: http://ui.ncb.cloud
  only:
  - master
