stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: echo "Running tests"

build:
  stage: build
  script: 
    - echo "Building App"
    - npm -v

deploy_development:
  stage: deploy
  script:
    - echo "Deploy to development server"
  environment:
    name: development
    url: http://ui.ncb.cloud
  only:
  - master
