stages:
  # - test
  - build
  - deploy

# test:
#   stage: test
#   script: echo "Running tests"
cache:
  paths:
  - build

build:
  stage: build
  script: 
    - node -v && npm -v
    - npm install
    - gulp html
    - gulp sass
    - gulp css
    - gulp img
    - gulp js
    - ls -la
    - rm -r build/builds/*
    - zip -r dist.zip build/
    # - mkdir build/builds/
    - mv dist.zip build/builds/dist-$CI_PIPELINE_ID.zip

deploy_development:
  stage: deploy
  script:
    - echo "Deploy to development server"
    - ls -la
    - pwd
    - whoami
    - rsync -r -v build oraneedwards@ui.ncb.cloud:/home/oraneedwards
  environment:
    name: development
    url: http://ui.ncb.cloud
  only:
  - master
