stages:
  # - test
  - build
  - deploy

# test:
#   stage: test
#   script: echo "Running tests"
cache:
  paths:
  - build

build:
  stage: build
  script: 
    - node -v && npm -v
    - npm install
    - gulp html
    - gulp css
    - ls -la

deploy_development:
  stage: deploy
  script:
    - echo "Deploy to development server"
    - ls -la
    - pwd
    - whoami
    - rsync -r -v build oraneedwards@ui.ncb.cloud:/home/oraneedwards
  environment:
    name: development
    url: http://ui.ncb.cloud
  only:
  - master
